name: {{analyzer_name.snakeCase()}}
description: An analytic tool that analyze and improve software quality.
version: 1.0.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  linter: ^1.14.0
  test: ^1.21.0
  build_runner: ^2.3.3

dependencies:
  analyzer: ">=5.1.0 <5.9.0"
  analyzer_plugin: ">=0.11.0 <0.12.0"
  collection: ^1.16.0
  file: ^6.0.0
  glob: ^2.0.1
  path: ^1.8.0
  source_span: ^1.8.0
  yaml: ^3.1.0
